import type { UserItem } from "./allUsersColumns";

export const allUsersData: UserItem[] = [
  {
    id: "u_001",
    name: "Alice Johnson",
    username: "alice_j",
    email: "alice.johnson@example.com",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    posts: 190,
    status: "active",
    createdAt: "2025-01-03T09:15:00.000Z",
  },
  {
    id: "u_002",
    name: "Sharath Kumar",
    username: "sharath_k",
    email: "sharath.kumar@example.com",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    posts: 42,
    status: "pending",
    createdAt: "2025-01-03T10:05:00.000Z",
  },
  {
    id: "u_003",
    name: "Maya Patel",
    username: "maya_p",
    email: "maya.patel@example.com",
    avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    posts: 78,
    status: "inactive",
    createdAt: "2025-01-02T14:30:00.000Z",
  },
  {
    id: "u_004",
    name: "Omar Rizvi",
    username: "omar_r",
    email: "omar.rizvi@example.com",
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    posts: 5,
    status: "active",
    createdAt: "2025-02-11T08:45:00.000Z",
  },
  {
    id: "u_005",
    name: "Sara Connors",
    username: "sara_c",
    email: "sara.connors@example.com",
    avatar: "https://randomuser.me/api/portraits/women/19.jpg",
    posts: 12,
    status: "active",
    createdAt: "2025-03-22T11:00:00.000Z",
  },
  {
    id: "u_006",
    name: "Luca Moretti",
    username: "luca_m",
    email: "luca.moretti@example.com",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    posts: 34,
    status: "active",
    createdAt: "2025-04-10T07:25:00.000Z",
  },
  {
    id: "u_007",
    name: "Hannah Lee",
    username: "hannah_l",
    email: "hannah.lee@example.com",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    posts: 87,
    status: "pending",
    createdAt: "2025-05-15T16:40:00.000Z",
  },
  {
    id: "u_008",
    name: "Diego Fernandez",
    username: "diego_f",
    email: "diego.fernandez@example.com",
    avatar: "https://randomuser.me/api/portraits/men/56.jpg",
    posts: 3,
    status: "inactive",
    createdAt: "2025-06-01T12:10:00.000Z",
  },
  {
    id: "u_009",
    name: "Emma Wilson",
    username: "emma_w",
    email: "emma.wilson@example.com",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    posts: 210,
    status: "active",
    createdAt: "2025-06-18T09:50:00.000Z",
  },
  {
    id: "u_010",
    name: "Noah Smith",
    username: "noah_s",
    email: "noah.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/men/77.jpg",
    posts: 58,
    status: "active",
    createdAt: "2025-07-02T13:20:00.000Z",
  },
  {
    id: "u_011",
    name: "Yara Haddad",
    username: "yara_h",
    email: "yara.haddad@example.com",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    posts: 27,
    status: "pending",
    createdAt: "2025-07-19T18:05:00.000Z",
  },
  {
    id: "u_012",
    name: "Kenji Tanaka",
    username: "kenji_t",
    email: "kenji.tanaka@example.com",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    posts: 9,
    status: "active",
    createdAt: "2025-08-01T10:00:00.000Z",
  },
];

export default allUsersData;
